USE [master]
GO

/****** Object:  Database [DigiCallGroupDev]    Script Date: 2017/08/31 1:14:38 PM ******/
CREATE DATABASE [DigiCallGroupDev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DigiCallGroupDev', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DigiCallGroupDevDev.mdf' , SIZE = 48832KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DigiCallGroupDev_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DigiCallGroupDevDev_log.ldf' , SIZE = 1600KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DigiCallGroupDev] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DigiCallGroupDev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DigiCallGroupDev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET ARITHABORT OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DigiCallGroupDev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DigiCallGroupDev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DigiCallGroupDev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DigiCallGroupDev] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DigiCallGroupDev] SET  MULTI_USER 
GO

ALTER DATABASE [DigiCallGroupDev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DigiCallGroupDev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DigiCallGroupDev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DigiCallGroupDev] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DigiCallGroupDev] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DigiCallGroupDev] SET QUERY_STORE = OFF
GO

USE [DigiCallGroupDev]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DigiCallGroupDev] SET  READ_WRITE 
GO


